# SAM configuration file
version = 0.1

[default.global.parameters]
stack_name = "product-catalog-api-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "product-catalog-api-dev"
parameter_overrides = "Environment=dev"

[default.local_start_api.parameters]
warm_containers = "EAGER"
debug_port = 5858
parameter_overrides = "Environment=dev"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
debug_port = 5858
