name: "Terraform Code Checks"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Format and syntax Validation"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5
          terraform_wrapper: false

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: true

      - name: Format Status
        if: steps.fmt.outcome == 'failure'
        run: |
          echo "Terraform formatting check has failed. Please run 'terraform fmt -recursive' to fix formatting issues."
          exit 1

      - name: Validation Status
        if: steps.validate.outcome == 'failure'
        run: |
          echo "Terraform syntax validation failed. Please check your Terraform configuration for errors."
          exit 1
